name: housebarber
description: Barbudos Agendamento.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mongo_dart: ^0.7.0-nullsafety.3
  liquid_swipe: ^2.1.0
  crypto: ^3.0.1
  intl: ^0.17.0
  convex_bottom_bar: ^3.0.0
  money_formatter: ^0.0.3
  shared_preferences: ^2.0.5
  syncfusion_flutter_calendar: ^19.1.54+1
  dropdown_search: ^0.6.1
  easy_mask: ^1.1.5
  image_picker: ^0.7.4
  background_fetch: ^0.7.2
  rxdart: ^0.27.0
  flutter_local_notifications: ^5.0.0
  get: ^4.1.4
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  web_socket_channel: ^2.1.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imagens/backgroud-new-client.jpg
    - assets/imagens/backgroud-new-produto-servico.jpg
    - assets/imagens/barber.jpg
    - assets/imagens/arraste_lados.gif
    - assets/imagens/barber-shop.gif
    - assets/imagens/barber-shop.png
    - assets/imagens/fundo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/imagens/barber-shop.png"
  adaptive_icon_background: "assets/imagens/fundo.png"
  adaptive_icon_foreground: "assets/imagens/barber-shop.png"

flutter_native_splash:
  background_image: "assets/imagens/fundo.png"
  image: assets/imagens/barber-shop.png
